### ISSUE TITLE
Reduce duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [abdisome/prj-rev-bwfs-dasmoto#4]
When writing CSS, it's best practice to be efficient as possible. In this case four if your sections have the same font. Instead of applying the family four different times it's best to do the following:

Either:
```CSS
p,
h1,
h2,
h3 {
  font-family: "Helvetica", serif;
}
```
Or:
```CSS
body {
  font-family: "Helvetica", serif;
}
```

https://github.com/abdisome/prj-rev-bwfs-dasmoto/blob/56daf1952ca590794d339207b05792846dc31780/DasmotoProject/Resources/css/style.css#L1-L29
